### PR TITLE
Support symfony 3 too

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Needed so that the laravel adapter works on Laravel 5.3 too. ;)

**Comment by GrahamCampbell** [comment]
NB Not strict needed for Laravel 5.2, but is a nice to have.

**Comment by GrahamCampbell** [comment]
For some context:
- 5.2: https://github.com/laravel/framework/blob/5.2/composer.json
- 5.3: https://github.com/laravel/framework/blob/master/composer.json

**Comment by reinink** [comment]
Awesome! Thanks Graham.

**Comment by reinink** [comment]
Question, do you think I should just delete and recreate the 1.0.0 tag for this release, or just create a new 1.0.1 release?

**Comment by GrahamCampbell** [comment]
Just create a new release. ;)

**Comment by GrahamCampbell** [comment]
The only case where I'd recommend re-tagging is if the dependencies were too open. ;)

**Comment by reinink** [comment]
Already done, thanks! :+1:

**Pull request merged**
