### PR TITLE
Use Glide 2.0

### PR DESCRIPTION
**Pull request by Lustmored**
Since Glide have recently updated to version 2.0 this adapter should follow. This simple change adapts `SymfonyRequestFactory` to Flysystem 2 and update dependency on `league/glide`

### CODE REVIEW

**Comment by tgalopin** [comment]
Ah, I think we need to release 2.0 for all adapters then right?

**Comment by Lustmored** [comment]
I believe so as change in `SymfonyRequestFactory` is definitely backwards incompatible.

I am only using symfony one, but changes are trivial so I can provide PRs for each of them if that'd help.

**Comment by Lustmored** [comment]
I have created PRs in all glide-* packages in thephpleague to ease your work - they are as trivial as one can get.

So it's just a case of accepting them and releasing 2.0 :)

**Comment by tgalopin** [comment]
I guess we should fix tests in the adapters, as this PR wouldn't pass tests (the test relies in FilesystemInterface).

If you have time to migrate to Github Actions that would be awesome, otherwise I'll have a look when I can.

**Comment by Lustmored** [comment]
I will take a look and come back in a day or two with updated PR or comment that I have failed 👍

**Comment by Lustmored** [comment]
I have updates tests, phpunit and mockery and created github actions file. You can see working run here:

https://github.com/Lustmored/glide-symfony/runs/2075558675

I don't know why it doesn't show up in PR - maybe if actions config is only in PR but not in main branch it doesn't run?

But on my fork CI runs and all tests for code in this PR pass. If you will accept changes I will propagate similar changes to glide-* PRs.

**Comment by Lustmored** [comment]
@tgalopin just a friendly reminder

**Comment by tgalopin** [comment]
Thanks for the reminder :) . Tests are passing on master!

**Comment by Lustmored** [comment]
> Thanks for the reminder :) . Tests are passing on master!

That's good to hear. I will update PRs on other glide-* repositories in a few days probably :+1:

**Comment by Lustmored** [comment]
@tgalopin it would be great if you could tag 2.0 here and hopefully merge and tag new versions on other glide-* packages. No pressure, just a reminder :)

**Pull request merged**
