### PR TITLE
Introduce Symfony 4 compatibility

### PR DESCRIPTION
**Pull request by brainrepo**

### CODE REVIEW

**Comment by mmarchois** [comment]
Hi, when this PR will be merge?

**Comment by mmarchois** [comment]
Hi, when this PR will be merge?

**Review by mmarchois — APPROVED** [review]

**Comment by erikgaal** [comment]
@reinink Can you give any update on whether you are going to merge this PR?

**Comment by reinink** [comment]
@erikgaal Now :)

Sorry for the delay on this folks.

**Comment by reinink** [comment]
Also tagged: https://github.com/thephpleague/glide-symfony/releases/tag/1.0.3

**Comment by erikgaal** [comment]
@reinink Thanks a lot! 👍

**Pull request merged**
